return {
  require 'ben.plugins.theme',
  require 'ben.plugins.telescope',
  require 'ben.plugins.treesitter',
  require 'ben.plugins.lsp-config',
  require 'ben.plugins.blink',
  require 'ben.plugins.which-key',
  require 'ben.plugins.undotree',
  require 'ben.plugins.snacks',
  require 'ben.plugins.conform',
  require 'ben.plugins.lint',
  require 'ben.plugins.yanky',
  require 'ben.plugins.mini',
  require 'ben.plugins.debug',
  require 'ben.plugins.indent-line',
  require 'ben.plugins.autopairs',
  require 'ben.plugins.gitsigns',
  require 'ben.plugins.neotree',
  require 'ben.plugins.fugitive',
  require 'ben.plugins.bufferline',
  require 'ben.plugins.rustaceanvim',
  require 'ben.plugins.copilot',
  require 'ben.plugins.code-companion',
  {
    'NMAC427/guess-indent.nvim',
  },
  { 'folke/todo-comments.nvim', event = 'VimEnter', dependencies = { 'nvim-lua/plenary.nvim' }, opts = {} },
  { 'nvim-treesitter/nvim-treesitter-context' },
}
